apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: beslutteroversikt
  namespace: default
  cluster: prod-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/beslutteroversikt/beslutteroversikt:{{version}}
  port: 8080
  liveness:
    path: beslutteroversikt/internal/isAlive
    initialDelay: 15
  readiness:
    path: beslutteroversikt/internal/isReady
    initialDelay: 15
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 1Gi
  ingresses:
    - https://beslutteroversikt.nais.adeo.no
    - https://app.adeo.no/beslutteroversikt
  envFrom:
    - configmap: pto-config
