apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: beslutteroversikt
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/beslutteroversikt/beslutteroversikt:{{version}}
  port: 8080
  webproxy: true
  liveness:
    path: beslutteroversikt/internal/isAlive
    initialDelay: 15
  readiness:
    path: beslutteroversikt/internal/isReady
    initialDelay: 15
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 1Gi
  ingresses:
    - https://beslutteroversikt-q1.nais.preprod.local
    - https://app.dev.adeo.no/beslutteroversikt
    - https://app-q1.dev.adeo.no/beslutteroversikt
    - https://app-q1.adeo.no/beslutteroversikt
  envFrom:
    - configmap: pto-config
