apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: beslutteroversikt
  namespace: obo
  labels:
    team: obo
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  ingresses:
    - https://beslutteroversikt.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 75
  resources:
    requests:
      cpu: 500m
      memory: 500Mi
    limits:
      cpu: "1"
      memory: 1Gi
  secureLogs:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: obo-beslutteroversikt-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: modiacontextholder
          namespace: personoversikt
      external:
        - host: veilarbveileder.prod-fss-pub.nais.io
        - host: veilarbvedtaksstotte.prod-fss-pub.nais.io
  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "obo-beslutteroversikt-prod"
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://cdn.nav.no/personoversikt/internarbeidsflate-decorator-v3/prod",
              "preserveFromPath": false
            },
            {
              "fromPath": "/veilarbpersonflate/*",
              "toUrl": "https://veilarbpersonflate.intern.nav.no",
              "preserveFromPath": true
            }
          ],
          "proxies": [
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "http://modiacontextholder.personoversikt",
              "preserveFromPath": false,
              "toApp": {
                "name": "modiacontextholder",
                "namespace": "personoversikt",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "https://veilarbveileder.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
              "name": "veilarbveileder",
              "namespace": "pto",
              "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "https://veilarbvedtaksstotte.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
              "name": "veilarbvedtaksstotte",
              "namespace": "pto",
              "cluster": "prod-fss"
              }
            }
          ]
        }
