apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: beslutteroversikt
  namespace: obo
  labels:
    team: obo
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2025.01.07_14.40-566d5f5c0dff
  port: 8080
  ingresses:
    - https://beslutteroversikt.intern.dev.nav.no
    - https://beslutteroversikt.ansatt.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
  secureLogs:
    enabled: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: obo-beslutteroversikt-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: modiacontextholder
          namespace: personoversikt
        - application: veilarbvedtaksstotte
          namespace: obo
        - application: veilarbveileder
          namespace: obo
        - application: obo-unleash
          namespace: obo
  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "obo-beslutteroversikt-dev"
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no"]
            },
            "corp": {
              "policy": "cross-origin"
            }
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://cdn.nav.no/personoversikt/internarbeidsflate-decorator-v3/dev",
              "preserveFromPath": false
            },
            {
              "fromPath": "/veilarbpersonflate/*",
              "toUrl": "https://veilarbpersonflate.intern.dev.nav.no",
              "preserveFromPath": false
            }
          ],
          "proxies": [
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "http://modiacontextholder.personoversikt",
              "preserveFromPath": false,
              "toApp": {
                "name": "modiacontextholder",
                "namespace": "personoversikt",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "http://veilarbveileder.obo",
              "preserveFromPath": true,
              "toApp": {
              "name": "veilarbveileder",
              "namespace": "obo",
              "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "http://veilarbvedtaksstotte.obo",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbvedtaksstotte",
                "namespace": "obo",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/obo-unleash",
              "toUrl": "http://obo-unleash.obo",
              "preserveFromPath": false,
              "toApp": {
                "name": "obo-unleash",
                "namespace": "obo",
                "cluster": "dev-gcp"
              }
            }
          ]
        }
