name: paoa frontend container prod

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/poao-frontend-container-prod.yaml'
      - '.nais/obo-nais-prod.yaml'
  workflow_dispatch:

concurrency:
  group: pto_frontend_container_prod
  cancel-in-progress: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: deploy gcp prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/obo-nais-prod.yaml
